# Generated by Django 6.1.1 on 2026-09-12 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_auction', 'In auction'), ('funded', 'Funded'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='empresas.company')),
                ('debtor_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='empresas.debtorclient')),
            ],
        ),
    ]
