# Generated by Django 6.1.1 on 2026-09-13 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_company_annual_revenue_company_data_as_of_and_more'),
        ('facturas', '0002_invoicebatch_invoice_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('APPROVE', 'Approve'), ('REVIEW', 'Manual review'), ('REJECT', 'Reject')], max_length=10)),
                ('rating', models.CharField(max_length=1)),
                ('risk_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('probability_of_default', models.DecimalField(decimal_places=6, max_digits=7)),
                ('loss_given_default', models.DecimalField(decimal_places=6, max_digits=7)),
                ('exposure_at_default', models.DecimalField(decimal_places=2, max_digits=14)),
                ('expected_default_loss', models.DecimalField(decimal_places=2, max_digits=14)),
                ('expected_dilution_loss', models.DecimalField(decimal_places=2, max_digits=14)),
                ('expected_loss', models.DecimalField(decimal_places=2, max_digits=14)),
                ('confidence', models.CharField(max_length=20)),
                ('term_days', models.PositiveIntegerField(default=0)),
                ('reference_rate', models.DecimalField(decimal_places=7, max_digits=8)),
                ('reference_rate_as_of', models.DateField()),
                ('reference_rate_source', models.URLField()),
                ('recommended_annual_rate', models.DecimalField(decimal_places=7, max_digits=8)),
                ('recommended_monthly_rate', models.DecimalField(decimal_places=7, max_digits=8)),
                ('recommended_advance_percentage', models.DecimalField(decimal_places=3, max_digits=6)),
                ('financing_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('net_disbursement', models.DecimalField(decimal_places=2, max_digits=14)),
                ('expected_investor_profit', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reasons', models.JSONField(default=list)),
                ('warnings', models.JSONField(default=list)),
                ('input_snapshot', models.JSONField(default=dict)),
                ('policy_version', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='cfdi_uuid',
            field=models.CharField(blank=True, default='', max_length=36),
        ),
        migrations.AddField(
            model_name='invoice',
            name='currency',
            field=models.CharField(default='MXN', max_length=3),
        ),
        migrations.AddField(
            model_name='invoice',
            name='demo_scenario',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='invoice',
            name='has_delivery_evidence',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_disputed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_previously_assigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='issuer_rfc',
            field=models.CharField(blank=True, default='', max_length=13),
        ),
        migrations.AddField(
            model_name='invoice',
            name='outstanding_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(default='PPD', max_length=3),
        ),
        migrations.AddField(
            model_name='invoice',
            name='receiver_rfc',
            field=models.CharField(blank=True, default='', max_length=13),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sat_status',
            field=models.CharField(default='vigente', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sat_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='xml_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='invoice_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('outstanding_balance__isnull', True), ('outstanding_balance__gt', 0), _connector='OR'), name='invoice_outstanding_balance_positive'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('due_date__gte', models.F('issue_date'))), name='invoice_due_on_or_after_issue'),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments', to='facturas.invoice'),
        ),
    ]
