# Generated by Django 6.1.1 on 2026-09-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0003_riskassessment_invoice_cfdi_uuid_invoice_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicebatch',
            name='factoring_term_days',
            field=models.PositiveSmallIntegerField(choices=[(30, '30 days'), (60, '60 days'), (90, '90 days')], default=30),
        ),
    ]
