import { formatCents } from "@/lib/marketplace";
import type { FinancierDashboardData } from "@/lib/financier-dashboard";
import { DashboardKpi } from "./dashboard-kpi";
import { CapitalChart, Opportunities, PortfolioDistribution, RecentOperations } from "./dashboard-panels";

export function FinancierDashboardContent({ data }: { data: FinancierDashboardData }) {
  const date = new Intl.DateTimeFormat("es-MX", { weekday: "long", day: "numeric", month: "long", year: "numeric", timeZone: "America/Mexico_City" }).format(new Date());
  return <div className="mx-auto max-w-[1380px]"><header className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-[38px] font-bold leading-none tracking-[-.04em] text-navy">Dashboard</h1><p className="mt-1.5 text-[17px] text-[#1d54b7]">Tu capital, en movimiento.</p></div><div className="text-right text-xs leading-5 text-[#1d54b7]"><strong className="block capitalize text-navy">{date}</strong><span>Aquí está el resumen de tu portafolio.</span></div></header><section className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4"><DashboardKpi label="Disponible para financiar" value={`${formatCents(data.availableCapitalCents)}${data.availableCapitalCents === null ? "" : " MXN"}`} detail="Fondos disponibles para nuevas oportunidades" icon="wallet" tone="blue"/><DashboardKpi label="Capital financiado" value={`${formatCents(data.financedCapitalCents)}${data.financedCapitalCents === null ? "" : " MXN"}`} detail="Capital asociado a esta cuenta" icon="coins" tone="green"/><DashboardKpi label="Retorno generado" value={`${formatCents(data.generatedReturnCents)}${data.generatedReturnCents === null ? "" : " MXN"}`} detail="Ganancia de operaciones completadas" icon="percent" tone="violet"/><DashboardKpi label="Operaciones activas" value={data.activeOperationsCount === null ? "—" : String(data.activeOperationsCount)} detail="Financiamientos en curso" icon="bars" tone="teal"/></section><div className="mt-4 grid gap-4 xl:grid-cols-[1.25fr_1fr]"><CapitalChart history={data.capitalHistory}/><Opportunities opportunities={data.opportunities}/><RecentOperations operations={data.recentOperations}/><PortfolioDistribution byRisk={data.portfolioByRisk}/></div></div>;
}
