import { Icon } from "../icons";
import { buildLiquidityDemo } from "@/lib/sme-dashboard-demo";

export function LiquidityProjection({ receivablesAmount, eligibleAmount, financedAmount }: { receivablesAmount: number; eligibleAmount: number; financedAmount: number }) {
  const points = buildLiquidityDemo({ receivablesAmount, eligibleAmount, financedAmount });
  const max = Math.max(...points.map((point) => point.withFactora), 1);
  const coordinates = (key: "withFactora" | "withoutFinancing") => points.map((point, index) => ({ x: 58 + index * 104, y: 175 - (point[key] / max) * 145 }));
  const withFactora = coordinates("withFactora");
  const withoutFinancing = coordinates("withoutFinancing");
  const path = (values: { x: number; y: number }[]) => values.map((point) => `${point.x},${point.y}`).join(" ");
  return <section className="min-h-[360px] rounded-xl border border-slate-200 bg-white p-5 shadow-[0_7px_22px_rgba(15,31,68,.025)]"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="flex items-center gap-2 text-lg font-bold text-navy">Proyección de liquidez <Icon name="help" size={16} className="text-[#52688f]"/></h2><p className="mt-1 text-sm text-[#52688f]">Comparativa de flujo de efectivo con y sin financiamiento.</p></div><button className="flex h-10 items-center gap-8 rounded-lg border border-slate-200 px-4 text-xs text-navy">Próximos 6 meses <Icon name="chevron" size={15}/></button></div><div className="mt-3 overflow-x-auto"><svg viewBox="0 0 620 215" className="h-[215px] min-w-[560px] w-full" role="img" aria-label="Proyección demo de liquidez para los próximos seis meses"><g stroke="#e7edf5">{[30, 78, 126, 175].map((y) => <line key={y} x1="38" x2="592" y1={y} y2={y}/>)}</g><polygon points={`${path(withFactora)} 578,175 58,175`} fill="#22c55e" opacity=".08"/><polyline points={path(withoutFinancing)} fill="none" stroke="#8798ba" strokeWidth="2"/><polyline points={path(withFactora)} fill="none" stroke="#16a34a" strokeWidth="2.5"/>{points.map((point, index) => <g key={point.label}><circle cx={withoutFinancing[index].x} cy={withoutFinancing[index].y} r="4" fill="#8798ba" stroke="white" strokeWidth="1.5"/><circle cx={withFactora[index].x} cy={withFactora[index].y} r="4.5" fill="#16a34a" stroke="white" strokeWidth="1.5"/><text x={withFactora[index].x} y="201" textAnchor="middle" fill="#52688f" fontSize="11">{point.label}</text></g>)}</svg></div><div className="flex justify-center gap-7 text-xs text-[#52688f]"><span className="flex items-center gap-2"><i className="h-3 w-3 rounded-full bg-green-500"/>Con Factora</span><span className="flex items-center gap-2"><i className="h-3 w-3 rounded-full bg-[#8798ba]"/>Sin financiamiento</span></div></section>;
}
