# Generated by Django 6.1.1 on 2026-09-13 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0003_riskassessment_invoice_cfdi_uuid_invoice_currency_and_more'),
        ('mercado', '0002_offer_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='risk_assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='facturas.riskassessment'),
        ),
    ]
