# Generated by Django 6.1.1 on 2026-09-12 20:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymenthistory',
            options={'ordering': ['paid_at']},
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='paid_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
