# Generated by Django 6.1.1 on 2026-09-12 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_alter_paymenthistory_options_paymenthistory_paid_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='nessie_account_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='company',
            name='nessie_customer_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='nessie_deposit_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
