# Generated by Django 6.1.1 on 2026-09-13 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_company_nessie_account_id_company_nessie_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='annual_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='data_as_of',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='data_source',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='dilution_rate',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='company',
            name='dispute_rate',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='company',
            name='scian_sector',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='company',
            name='source_reference',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='company',
            name='years_operating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='debtorclient',
            name='bureau_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='debtorclient',
            name='current_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='debtorclient',
            name='data_as_of',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='debtorclient',
            name='data_source',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='debtorclient',
            name='debt_to_ebitda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='debtorclient',
            name='employee_band',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='debtorclient',
            name='has_legal_events',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='debtorclient',
            name='operating_margin',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='debtorclient',
            name='rfc',
            field=models.CharField(blank=True, default='', max_length=13),
        ),
        migrations.AddField(
            model_name='debtorclient',
            name='scian_sector',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='debtorclient',
            name='source_reference',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='debtorclient',
            name='years_operating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='due_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='issued_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
