# Generated by Django 6.1.1 on 2026-09-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('risk_profile', models.CharField(max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
