# Generated by Django 6.1.1 on 2026-09-12 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiadoras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lender',
            name='nessie_account_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='lender',
            name='nessie_customer_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
