# Generated by Django 6.1.1 on 2026-09-13 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiadoras', '0002_lender_nessie_account_id_lender_nessie_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lender',
            name='available_capital',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
