import { formatCents, type MarketplaceOpportunity } from "@/lib/marketplace";
import { RiskBadge, HistoryBadge } from "./marketplace-badges";

export function MarketplaceTable({ opportunities }: { opportunities: MarketplaceOpportunity[] }) {
  return <div className="overflow-x-auto"><table className="w-full min-w-[1080px] border-collapse text-left"><thead className="bg-[#f1f5fa] text-xs font-medium text-[#38517d]"><tr><th className="px-4 py-3">Factura</th><th className="px-4 py-3">Deudor (pagador)</th><th className="px-4 py-3">Monto</th><th className="px-4 py-3">Plazo est.</th><th className="px-4 py-3">Riesgo</th><th className="px-4 py-3">Retorno est.</th><th className="px-4 py-3">Historial</th><th className="px-4 py-3">Acción</th></tr></thead><tbody>{opportunities.map((item) => <tr key={item.id} className="border-t border-slate-200 text-[13px] text-navy transition hover:bg-slate-50/70"><td className="px-4 py-2.5"><strong className="block">{item.folio}</strong><span className="mt-1 block text-[11px] text-[#1d54b7]">{item.formattedIssueDate}</span></td><td className="px-4 py-2.5"><span className="flex items-center gap-2.5"><i className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-[#e9f2ff] text-[10px] font-bold not-italic text-[#1d54b7]">{item.debtorInitials}</i><span>{item.debtor}</span></span></td><td className="px-4 py-2.5"><strong className="block">{item.formattedAmount}</strong><span className="mt-1 block text-[11px] text-[#1d54b7]">MXN</span></td><td className="px-4 py-2.5 text-[#1d54b7]">{item.daysUntilDue > 0 ? `${item.daysUntilDue} días` : "—"}</td><td className="px-4 py-2.5"><RiskBadge risk={item.risk}/></td><td className="px-4 py-2.5"><EstimatedReturn item={item}/></td><td className="px-4 py-2.5"><HistoryBadge known={item.previouslyFinanced}/></td><td className="px-4 py-2.5"><button type="button" className="min-w-[120px] cursor-default rounded-lg border border-[#cbdcf6] bg-[#f4f8ff] px-4 py-2 text-xs font-semibold text-[#124fc4]" aria-label={`Detalles de ${item.folio}, próximamente`}>Ver detalles</button></td></tr>)}</tbody></table></div>;
}

function EstimatedReturn({ item }: { item: MarketplaceOpportunity }) {
  if (item.estimatedReturnRate === null) return <span className="text-[#6b7fa5]">—</span>;
  return <><strong className="block">{item.estimatedReturnRate}%</strong><span className="mt-1 block text-[11px] text-[#1d54b7]">{item.estimatedReturnCents === null ? "—" : `${formatCents(item.estimatedReturnCents)} MXN`}</span></>;
}
